config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users
  
  root to: "blabs#index"
  
  resources :blabs do
    member do
      put "like" => "blabs#upvote"
      put "dislike" => "blabs#downvote"
    end
    resources :comments
  end
  
  resources :users
  
      

end

app/models/blab.rb
class Blab < ActiveRecord::Base
    #association added for voting capabilities 
    acts_as_votable
    #association added so that non-user can skip to url to add a blab
    belongs_to :user
    belongs_to :category
    has_many :comments 
    has_attached_file :image, styles: { large: "600x600", medium: "300x300", thumb: "150x150#"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :blabs
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blab
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #association added so that non user can skip to url to add a blab       
  has_many :blabs
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blabs_controller.rb
class BlabsController < ApplicationController
  before_action :set_blab, only: [:show, :edit, :update, :destroy]
  # added filter to stop non-users being able to delete blabs otherwise deletion of content could be done by anyone visiting the application. This code brings user back to index page if any blab option is clicked other than show and index
  # to be edited in views so links don't show.
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /blabs
  # GET /blabs.json
  def index
    # index page ordering all blabs by newest first (Top-down)
    @blabs = Blab.all.order("created_at DESC")
  end

  # GET /blabs/1
  # GET /blabs/1.json
  def show
  end

  # GET /blabs/new
  def new
    @blab = current_user.blabs.build
  end

  # GET /blabs/1/edit
  def edit
  end

  # POST /blabs
  # POST /blabs.json
  def create
    @blab = current_user.blabs.build(blab_params)

    respond_to do |format|
      if @blab.save
        format.html { redirect_to @blab, notice: 'Blab was successfully created.' }
        format.json { render :show, status: :created, location: @blab }
      else
        format.html { render :new }
        format.json { render json: @blab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blabs/1
  # PATCH/PUT /blabs/1.json
  def update
    respond_to do |format|
      if @blab.update(blab_params)
        format.html { redirect_to @blab, notice: 'Blab was successfully updated.' }
        format.json { render :show, status: :ok, location: @blab }
      else
        format.html { render :edit }
        format.json { render json: @blab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blabs/1
  # DELETE /blabs/1.json
  def destroy
    @blab.destroy
    respond_to do |format|
      format.html { redirect_to blabs_url, notice: 'Blab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # upvote and downvote methods with redirect to back button
  def upvote
    @blab = Blab.find(params[:id])
    @blab.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @blab = Blab.find(params[:id])
    @blab.downvote_by current_user
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blab
      @blab = Blab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blab_params
    # added permit attribute params here allows for the data to be saved to the database
      params.require(:blab).permit(:title, :body, :url, :category_id, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
    @blab = Blab.find(params[:blab_id])
    @comment = @blab.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @blab, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:blab_id, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blabs_helper.rb
module BlabsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blabs/_form.html.erb
 <%= form_for @blab, html: { multipart: true } do |f| %>
  <% if @blab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blab.errors.count, "error") %> prohibited this blab from being saved:</h2>

      <ul>
      <% @blab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- Bootstrap class form-group added for form content design -->
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id , Category.all, :id, :name, {prompt: "Choose a category"} %><br>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/blabs/edit.html.erb
<h1>Edit Your Blab</h1>

<!-- adds _form into page -->
<%= render 'form' %>

<!-- linking underneath form on page -->
<%= link_to 'Show', @blab %> |
<%= link_to 'Back', blabs_path %>

app/views/blabs/index.html.erb
<!-- if user not signed in - will show below message on index page -->
<% if !user_signed_in? %>
  <div class="jumpotron">
    <h1> Blab about what makes your city special </h1>
    <p><%= link_to "Sign Up To Write A Blab", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<!-- for each blap -->
<% @blabs.each do |blab| %>
    <!-- clear row to sperate each blab -->
    <div class="link row clearfix">
        <%= image_tag blab.image.url(:medium) %><br>
    
    <h2>
    <!-- Blab title  and followed by submitted by details -->
        <%= link_to blab.title, blab %><br>
        <small class="author">Submitted <%= time_ago_in_words(blab.created_at) %> ago by <%= blab.user.email %></small>
    </h2>
    
    <!-- voting buttons seperated withing its own div -->
      <div class="btn-group">
      <!-- for each link.its adding a link to the like link path and then making it a button. also added is a link to the url button -->
        <a class="btn btn-default btn-sm" href="<%= blab.url %>">Visit Site</a>
        <%= link_to like_blab_path(blab), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= blab.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_blab_path(blab), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Downvote
          <%= blab.get_downvotes.size %>
        <% end %>
      </div><!-- voting buttons div -->
    </div> <!-- Blab div -->
<% end %>

app/views/blabs/new.html.erb
<h1>New Blab</h1>

<%= render 'form' %>

<%= link_to 'Back', blabs_path %>

app/views/blabs/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @blab.image.url(:large) %>

<p>
  <strong>Title:</strong>
  <%= @blab.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blab.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @blab.url %>
</p>

<p>
  <strong>Published by:</strong>
  <%= @blab.user.email %>
</p>


<!-- like & dislike buttons added to show blab page -->
<div class="btn-group pull-right">
  <%= link_to like_blab_path(@blab), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Upvote
    <%= @blab.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_blab_path(@blab), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
    Downvote
    <%= @blab.get_downvotes.size %>
  <% end %>
</div>

<!-- Visit URL link button -->
<div class="btn-group">
	<%= link_to 'Visit URL', @blab.url, class: "btn btn-primary" %>
</div>

<!-- edit and destroy button coded only so that the user who created the code can see the buttons -->
<% if @blab.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_blab_path(@blab), class: "btn btn-default" %>
		<%= link_to 'Destroy', @blab, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>

<!-- comments section -->
<h3 class="comments_title">
  <%= @blab.comments.count %> Comments
</h3>

<!-- comments rendered to comments controller create method to be created upon submit -->
<div id="comments">
  <%= render :partial => @blab.comments %>
</div>
<%= simple_form_for [@blab, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>
<br>

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_header.html.erb
<!-- navbar styling using Bootsrap -->
    <!-- container for header with added bottom padding -->
  <header class="navbar navbar-default" role="navigation">
    <!-- Actual navbar contained within the navbar default -->
    <div class="navbar-inner">
        <!-- caontainer wraping logo and buttons -->
       <div class="container">
           <!-- logo container pulled left -->
         <div id="logo" class="navbar-brand"><%= link_to "Blabber", root_path %></div>
            <!-- User authentication - Links hidden based on user signed in or not -->
            <% if user_signed_in? %>
                <!-- logo buttons conatiner pulled to right -->
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Submit Blab', new_blab_path %></li>
                <li><%= link_to 'Account', edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              </ul>
            <% else %>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
              </ul>
            <% end %>
          </nav>
       </div> 
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blabber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- renders the code for the navbar bootstrap saved in the _header file / cleans up application page by sepeating content-->
  <%= render 'layouts/header' %>
  
  
  <div id="main_content" class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <!-- Wrapping of yield which imports the index into the application template -->
    <!-- Bootstrap column 9 block is centered -->
    <div id="content" class="col-md-9 center-block">
      <%= yield %>
    </div>
  </div>
  
  
</body>
</html>